services:
  _defaults:
    autowire: true
    autoconfigure: true

  # DataFixtures services for test environment
  QiniuStorageBundle\DataFixtures\:
    resource: '../../DataFixtures'
    tags: ['doctrine.fixture.orm']